/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package denemeApp;

import java.util.ArrayList;
import java.util.Arrays;

public class App {

    public static boolean search(ArrayList<Integer> array, int e) {
        System.out.println("inside search");
        if (array == null) return false;

        for (int elt : array) {
            if (elt == e) return true;
        }
        return false;
    }

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
        System.out.println(new App().search(array,4));
    }
}
